/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import Controler.controle;
import entidade.Usuario;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author octo
 */
public class tela1_Cadastro extends javax.swing.JFrame {

    controle controle = new controle();

    /**
     * Creates new form tela1_Cadastro
     */
    public tela1_Cadastro() {
        initComponents();
        montatabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_cadastrar = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        campo_idade = new javax.swing.JTextField();
        campo_cpf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_dados = new javax.swing.JTable();
        todos_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_cadastrar.setText("Cadastrar");
        BTN_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_cadastrarActionPerformed(evt);
            }
        });

        campo_nome.setText("Nome");

        campo_idade.setText("Idade");

        campo_cpf.setText("CPF");

        tabela_dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nome", "idade", "cpf"
            }
        ));
        jScrollPane1.setViewportView(tabela_dados);
        if (tabela_dados.getColumnModel().getColumnCount() > 0) {
            tabela_dados.getColumnModel().getColumn(0).setResizable(false);
            tabela_dados.getColumnModel().getColumn(1).setResizable(false);
            tabela_dados.getColumnModel().getColumn(2).setResizable(false);
        }

        todos_imprimir.setText("imprimirtodos");
        todos_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nome)
                            .addComponent(campo_idade)
                            .addComponent(campo_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(todos_imprimir)
                        .addGap(15, 15, 15))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campo_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campo_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_cadastrar)
                    .addComponent(todos_imprimir))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_cadastrarActionPerformed
        // TODO add your handling code here:

        String nome = campo_nome.getText();
        String idade = campo_idade.getText();
        String cpf = campo_cpf.getText();

        if (nome.isEmpty() || idade.isEmpty() || cpf.isEmpty()) {
            System.out.println("erro, Digite novamente");

        } else {
            Usuario a1 = new Usuario();
            a1.setCpf(cpf);
            a1.setIdade(idade);
            a1.setNome(nome);
            controle.salvar(a1);


        }

        campo_cpf.setText("");
        campo_idade.setText("");
        campo_nome.setText("");
        montatabela();
    }//GEN-LAST:event_BTN_cadastrarActionPerformed

    private void todos_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_imprimirActionPerformed
        // TODO add your handling code here:
        Usuario a1 = new Usuario();
        controle.imprimir(a1);
        
        
    }//GEN-LAST:event_todos_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_cadastrar;
    private javax.swing.JTextField campo_cpf;
    private javax.swing.JTextField campo_idade;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_dados;
    private javax.swing.JButton todos_imprimir;
    // End of variables declaration//GEN-END:variables

    private void montatabela() {

        ArrayList<Usuario> Lista = controle.consultar();

        if (Lista == null) {
            System.out.println("Ocorreu um erro");
        } else {
            tabela_dados.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "Código";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Idade";
                        case 3:
                            return "CPF";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 4;
                }

                @Override
                public int getRowCount() {
                    return Lista.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Usuario a1 = Lista.get(rowIndex);

                    if (a1 != null) {
                        switch (columnIndex) {
                            case 0:
                                return a1.getId();
                            case 1:
                                return a1.getNome();
                            case 2:
                                return a1.getIdade();
                            case 3:
                                return a1.getCpf();

                        }

                    }

                    return "n/d";
                }
            });

            tabela_dados.getColumnModel().getColumn(0).setMinWidth(10);
            tabela_dados.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabela_dados.getColumnModel().getColumn(0).setMaxWidth(20);
        }

    }
}
